### ISSUE TITLE
Suggestion: KI location name change

### ISSUE THREAD

**Issue by stoppableforce** [Kyuuden/Companion#1]
In the community, both 'Sealed Cave' and 'Luca' are commonly used to reference the Sealed Cave KI check, not the little girl in Dwarf Castle. Both because of that common shorthand for it as well as the fact that players who haven't played vanilla won't know who or what a Luca is, I'd suggest changing the name of the "Luca" KI check location to just "Dwarf Castle."

**Comment by Kyuuden** [comment]
Easy enough change. I used the list of key item locations from https://wiki.ff4fe.com/doku.php?id=developer_integration to populate the names.

**Comment by Kyuuden** [comment]
Fixed in 1.3.1
