### ISSUE TITLE
Boss Tracker 

### ISSUE THREAD

**Issue by frankiebones9089** [Kyuuden/Companion#4]
Minor but when you click into the lua to track a boss manually Bizhawk doesn't accept background inputs even with that option selected. You have to click back into Bizhawk to get inputs back. I'm boss tracking via Scala's webpage, it saves time. I have no idea if this is a bizhawk fix our a tracker fix but thought I'd bring it up.

**Comment by Kyuuden** [comment]
Are you using keyboard or controller? I'll try to fix this for keyboard, but don't have a controller to test with.

**Comment by frankiebones9089** [comment]
I am using a controller.  I didn't think to try with a keyboard

**Comment by Kyuuden** [comment]
Please try new release, 1.3.2

**Comment by frankiebones9089** [comment]
It works! Thank you!
