### ISSUE TITLE
Bizhawk 2.9

### ISSUE THREAD

**Issue by frankiebones9089** [Kyuuden/Companion#6]
Something happened with my Bizhawk so had to delete and downloaded 2.9.  When trying to open the auto tracker I am getting this attached error message.  Could easily be user error on my end but wanted to send a note.
![image](https://user-images.githubusercontent.com/121654234/230824767-2f28dd83-eff9-413a-a71f-7a1b7fa47b50.png)

**Comment by Kyuuden** [comment]
I haven't tried Bizhawk 2.9 yet. I'll look into it.

**Comment by Kyuuden** [comment]
This was fixed in 1.4.0
